services:
    dmzx.supportticket.listener:
        class: dmzx\supportticket\event\listener
        arguments:
            - '@user'
            - '@request'
            - '@template'
            - '@config'
            - '@ext.manager'
        tags:
            - { name: event.listener }               